# Generated by Django 4.2.2 on 2023-06-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_alter_media_property_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
